#! /bin/sh
set -eu

INSTANCE=${1:?"Usage: $0 instance-name"}
AWS_CREDS=".aws/credentials"
SET_PATH="PATH=/sbin:/usr/sbin:/bin:/usr/bin:/usr/pkg/sbin:/usr/pkg/bin"
BOOTSTRAP_CMD="/usr/bootstrap.sh binpkg"
PKGIN_CMD="pkgin -y install py37-awscli"

if [ -f "${HOME}/${AWS_CREDS}" ]; then
	cat <<EOF | ssh ${INSTANCE} "mkdir -p .aws && cat >.aws/config"
[default]
region = us-east-1
EOF

	scp ${HOME}/${AWS_CREDS} ${INSTANCE}:.aws/credentials
fi

ssh ${INSTANCE} "${SET_PATH} ${BOOTSTRAP_CMD} && ${SET_PATH} ${PKGIN_CMD}"
