#!/usr/bin/env python3
import argparse

def find_ec2(region):
    command = "aws ec2 describe-images --owners 099720109477 --filters 'Name=name,Values=ubuntu/images/hvm-ssd/ubuntu-xenial-16.04-amd64-server-????????' 'Name=state,Values=available' --query 'sort_by(Images, &CreationDate)[-1].{name: Name, id: ImageId}' --output json --region us-east-1"


def main():
    parser = argparse.ArgumentParser(description="""Creates an instance
                                     suitable for the specified volume,
                                     attaches the volume to the instance,
                                     and remotely logs in on the instance
                                     and displays the disklabel of the attached
                                     volume.""")
    parser.add_argument('-v', required=True, metavar="volume-id",
                        help="id of the volume to mount")
    parser.parse_args()


if __name__ == "__main__":
    main()
